# Generated by Django 4.2.27 on 2026-02-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admin_access_requested_user_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DELETE_ISSUE', 'Deleted Issue'), ('DELETE_USER', 'Deleted User'), ('CREATE_USER', 'Created User'), ('UPDATE_USER', 'Updated User'), ('CHANGE_USER_ROLE', 'Changed User Role'), ('OTHER', 'Other Action')], help_text='Type of action performed', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('target_model', models.CharField(blank=True, help_text='Model affected by the action (e.g., Issue, User)', max_length=50)),
                ('target_id', models.IntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('target_info', models.TextField(blank=True, help_text='Additional information about the target (e.g., issue title, username)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('admin', models.ForeignKey(help_text='The administrator who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
