# Generated by Django 4.2.27 on 2026-02-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminactivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_access_requested',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_requested',
        ),
    ]
